# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('transcription', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='DTPAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('dtp_application', models.CharField(blank=True, max_length=256, null=True)),
                ('mac_or_windows', models.CharField(blank=True, choices=[('M', 'Mac'), ('W', 'Windows'), ('E', 'Either')], max_length=32, null=True)),
                ('lso_on_dtp', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TSRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('new_account', models.BooleanField()),
                ('tms_or_cat', models.CharField(blank=True, choices=[('GS', 'GlobalSight'), ('IWS', 'Idiom WorldServer (versions 8.x)'), ('SDL_TMS', 'SDL TMS'), ('SDL_GS', 'SDL GroupShare'), ('GL', 'GlobalLink'), ('SL', 'Smartlink'), ('TF', 'Transifex'), ('XTM', 'XTM'), ('Plunet', 'Plunet'), ('GTT', 'GTT'), ('CW', 'Cloudwords'), ('Asterix', 'Asterix'), ('MQ', 'MemoQ Server'), ('MC', 'MateCat'), ('Other', 'Other')], default='GS', max_length=128, null=True)),
                ('tms_login_info', models.TextField(blank=True, null=True)),
                ('path_to_source', models.TextField(blank=True, null=True)),
                ('sla_metrics_path', models.TextField(blank=True, null=True)),
                ('include_graphics', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=16, null=True)),
                ('editable_graphics_source_available', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=16, null=True)),
                ('include_pdf_files', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=16, null=True)),
                ('editable_pdf_source_available', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=16, null=True)),
                ('include_qa_testing', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=16, null=True)),
                ('number_of_rounds_testing', models.CharField(blank=True, choices=[(1, 'One'), (2, 'Two'), (3, 'Three')], max_length=8, null=True)),
                ('project_filetype_info', models.TextField(blank=True, null=True)),
                ('client_instructions', models.TextField(blank=True, null=True)),
                ('requested_due_date', models.DateTimeField(blank=True, null=True)),
                ('audio_asset', models.ManyToManyField(to='portal.AudioAsset')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Client')),
                ('dtp_asset', models.ManyToManyField(to='portal.DTPAsset')),
                ('source_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sourcelanguage', to='portal.Language')),
                ('target_languages', models.ManyToManyField(to='portal.Language')),
            ],
        ),
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('dub_or_subtitle', models.CharField(blank=True, choices=[('DUB', 'Dubbing'), ('SUB', 'Subtitle')], max_length=128, null=True)),
                ('onscreen_text', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=16, null=True)),
                ('transcription', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=16, null=True)),
                ('ts_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.TSRequest')),
            ],
        ),
    ]
