# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsrequest',
            name='path_to_source',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='tsrequest',
            name='tms_login_info',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
