# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20161201_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsrequest',
            name='sla_metrics_path',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
