# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20161201_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tsrequest',
            name='audio_asset',
        ),
        migrations.RemoveField(
            model_name='tsrequest',
            name='dtp_asset',
        ),
    ]
