# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20161201_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioasset',
            name='ts_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.TSRequest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dtpasset',
            name='ts_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.TSRequest'),
            preserve_default=False,
        ),
    ]
