# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20161201_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphicAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('editable_graphics_source_available', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=16, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tsrequest',
            name='editable_graphics_source_available',
        ),
        migrations.RemoveField(
            model_name='tsrequest',
            name='include_graphics',
        ),
        migrations.AddField(
            model_name='graphicasset',
            name='ts_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.TSRequest'),
        ),
    ]
