# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20161201_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('editable_pdf_source_available', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=16, null=True)),
                ('path_to_source', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tsrequest',
            name='editable_pdf_source_available',
        ),
        migrations.RemoveField(
            model_name='tsrequest',
            name='include_pdf_files',
        ),
        migrations.AddField(
            model_name='audioasset',
            name='path_to_source',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='dtpasset',
            name='path_to_source',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='graphicasset',
            name='path_to_source',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='videoasset',
            name='path_to_source',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='pdfasset',
            name='ts_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.TSRequest'),
        ),
    ]
