# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 22:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20161201_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tsrequest',
            old_name='number_of_rounds_testing',
            new_name='rounds_of_testing',
        ),
    ]
