# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20161201_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tsrequest',
            old_name='project_filetype_info',
            new_name='project_and_filetype_info',
        ),
    ]
