# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20161201_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tsrequest',
            name='tms_or_cat',
        ),
        migrations.AddField(
            model_name='tsrequest',
            name='tms_or_cat_tool',
            field=models.CharField(blank=True, choices=[('GS', 'GlobalSight'), ('IWS', 'Idiom WorldServer (versions 8.x)'), ('SDL_TMS', 'SDL TMS'), ('SDL_GS', 'SDL GroupShare'), ('GL', 'GlobalLink'), ('SL', 'Smartlink'), ('TF', 'Transifex'), ('XTM', 'XTM'), ('Plunet', 'Plunet'), ('GTT', 'GTT'), ('CW', 'Cloudwords'), ('Asterix', 'Asterix'), ('MQ', 'MemoQ Server'), ('MC', 'MateCat'), ('Other', 'Other')], default='GS', max_length=128, null=True, verbose_name='TMS or CAT tool used'),
        ),
    ]
