# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20161201_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='rounds_of_testing',
            field=models.CharField(blank=True, choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three')], max_length=8, null=True),
        ),
    ]
