# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_auto_20161201_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audioasset',
            options={'verbose_name_plural': 'Requests Assets: Audio'},
        ),
        migrations.AlterModelOptions(
            name='dtpasset',
            options={'verbose_name_plural': 'Requests Assets: DTP'},
        ),
        migrations.AlterModelOptions(
            name='graphicasset',
            options={'verbose_name_plural': 'Requests Assets: Graphics'},
        ),
        migrations.AlterModelOptions(
            name='pdfasset',
            options={'verbose_name_plural': 'Requests Assets: PDFs'},
        ),
        migrations.AlterModelOptions(
            name='videoasset',
            options={'verbose_name_plural': 'Requests Assets: Video'},
        ),
        migrations.AddField(
            model_name='request',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default='2016-08-08'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(blank=True, choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('HOLD', 'On Hold')], default='OPEN', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='include_qa_testing',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=16, null=True, verbose_name='Include QA testing'),
        ),
        migrations.AlterField(
            model_name='request',
            name='sla_metrics_path',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='SLA metrics path'),
        ),
        migrations.AlterField(
            model_name='request',
            name='tms_login_info',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='TMS login info'),
        ),
    ]
