# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_auto_20161202_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audioasset',
            options={'verbose_name_plural': 'Audio'},
        ),
        migrations.AlterModelOptions(
            name='dtpasset',
            options={'verbose_name_plural': 'DTP'},
        ),
        migrations.AlterModelOptions(
            name='graphicasset',
            options={'verbose_name_plural': 'Graphics'},
        ),
        migrations.AlterModelOptions(
            name='pdfasset',
            options={'verbose_name_plural': 'PDFs'},
        ),
        migrations.AlterModelOptions(
            name='videoasset',
            options={'verbose_name_plural': 'Video'},
        ),
        migrations.AlterField(
            model_name='request',
            name='rounds_of_testing',
            field=models.CharField(blank=True, choices=[('One', 'One'), ('Two', 'Two'), ('Three', 'Three')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='source_language',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sourcelanguage', to='portal.Language'),
        ),
    ]
