# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_auto_20161204_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='include_qa_testing',
        ),
        migrations.AlterField(
            model_name='request',
            name='rounds_of_testing',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('One', 'One'), ('Two', 'Two'), ('Three', 'Three')], max_length=8, null=True),
        ),
    ]
