# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_auto_20161205_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        )
    ]
