# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_auto_20161205_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='source_language',
            field=models.ForeignKey(blank=True, default=5, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sourcelanguage', to='portal.Language'),
        ),
    ]
